### ISSUE TITLE
Flask学习教程 Part1 Chapter1:Flask简介及安装

### ISSUE THREAD

**Issue by misakar** [RoseOu/RoseOu.github.io#1]

**Comment by RoseOu** [comment]
@neo1218 因为用virtualenv创建虚拟环境时会自动安装pip，还是说我应该单独讲一讲怎么装pip？

**Comment by misakar** [comment]
是先后顺序的问题，现讲如何在全局中安装pip，然后pip install virtualenv，virtualenv就装好了。

**Comment by RoseOu** [comment]
@neo1218 已改～
