### ISSUE TITLE
ExtDeprecationWarning

### ISSUE THREAD

**Issue by gitzxon** [RoseOu/RoseOu.github.io#3]
http://roseou.github.io/2016/05/15/script/

some warning when running `python hello.py`

ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  .format(x=modname), ExtDeprecationWarning

flask.ext.script is deprecated, please use flask_scipt instead.
`from flask_script import Manager`

**Comment by RoseOu** [comment]
Thank you~I have changed it. @gitzxon
